name: Deploy React Application
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Eslint Dependencies
        run: npm ci
      - name: Install dev dependencies  
        run: npm ci --only=dev  
      - name: Lint
        run: npm run lint